/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartographieRouteImport } from './routes/cartographie'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MonCompteRouteImport } from './routes/mon-compte'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as EntreprisesIdRouteImport } from './routes/entreprises.$id'
import { Route as EntreprisesNouvelleRouteImport } from './routes/entreprises.nouvelle'
import { Route as EntreprisesIdModifierRouteImport } from './routes/entreprises.$id_.modifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartographieRoute = CartographieRouteImport.update({
  id: '/cartographie',
  path: '/cartographie',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteRoute = MonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesIdRoute = EntreprisesIdRouteImport.update({
  id: '/entreprises/$id',
  path: '/entreprises/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesNouvelleRoute = EntreprisesNouvelleRouteImport.update({
  id: '/entreprises/nouvelle',
  path: '/entreprises/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesIdModifierRoute = EntreprisesIdModifierRouteImport.update({
  id: '/entreprises/$id_/modifier',
  path: '/entreprises/$id/modifier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartographie': typeof CartographieRoute
  '/connexion': typeof ConnexionRoute
  '/journal': typeof JournalRoute
  '/mon-compte': typeof MonCompteRoute
  '/pipeline': typeof PipelineRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/entreprises/$id': typeof EntreprisesIdRoute
  '/entreprises/nouvelle': typeof EntreprisesNouvelleRoute
  '/entreprises/$id/modifier': typeof EntreprisesIdModifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartographie': typeof CartographieRoute
  '/connexion': typeof ConnexionRoute
  '/journal': typeof JournalRoute
  '/mon-compte': typeof MonCompteRoute
  '/pipeline': typeof PipelineRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/entreprises/$id': typeof EntreprisesIdRoute
  '/entreprises/nouvelle': typeof EntreprisesNouvelleRoute
  '/entreprises/$id/modifier': typeof EntreprisesIdModifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartographie': typeof CartographieRoute
  '/connexion': typeof ConnexionRoute
  '/journal': typeof JournalRoute
  '/mon-compte': typeof MonCompteRoute
  '/pipeline': typeof PipelineRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/entreprises/$id': typeof EntreprisesIdRoute
  '/entreprises/nouvelle': typeof EntreprisesNouvelleRoute
  '/entreprises/$id_/modifier': typeof EntreprisesIdModifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartographie'
    | '/connexion'
    | '/journal'
    | '/mon-compte'
    | '/pipeline'
    | '/utilisateurs'
    | '/entreprises/$id'
    | '/entreprises/nouvelle'
    | '/entreprises/$id/modifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartographie'
    | '/connexion'
    | '/journal'
    | '/mon-compte'
    | '/pipeline'
    | '/utilisateurs'
    | '/entreprises/$id'
    | '/entreprises/nouvelle'
    | '/entreprises/$id/modifier'
  id:
    | '__root__'
    | '/'
    | '/cartographie'
    | '/connexion'
    | '/journal'
    | '/mon-compte'
    | '/pipeline'
    | '/utilisateurs'
    | '/entreprises/$id'
    | '/entreprises/nouvelle'
    | '/entreprises/$id_/modifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartographieRoute: typeof CartographieRoute
  ConnexionRoute: typeof ConnexionRoute
  JournalRoute: typeof JournalRoute
  MonCompteRoute: typeof MonCompteRoute
  PipelineRoute: typeof PipelineRoute
  UtilisateursRoute: typeof UtilisateursRoute
  EntreprisesIdRoute: typeof EntreprisesIdRoute
  EntreprisesNouvelleRoute: typeof EntreprisesNouvelleRoute
  EntreprisesIdModifierRoute: typeof EntreprisesIdModifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartographie': {
      id: '/cartographie'
      path: '/cartographie'
      fullPath: '/cartographie'
      preLoaderRoute: typeof CartographieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/$id': {
      id: '/entreprises/$id'
      path: '/entreprises/$id'
      fullPath: '/entreprises/$id'
      preLoaderRoute: typeof EntreprisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/nouvelle': {
      id: '/entreprises/nouvelle'
      path: '/entreprises/nouvelle'
      fullPath: '/entreprises/nouvelle'
      preLoaderRoute: typeof EntreprisesNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/$id_/modifier': {
      id: '/entreprises/$id_/modifier'
      path: '/entreprises/$id/modifier'
      fullPath: '/entreprises/$id/modifier'
      preLoaderRoute: typeof EntreprisesIdModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartographieRoute: CartographieRoute,
  ConnexionRoute: ConnexionRoute,
  JournalRoute: JournalRoute,
  MonCompteRoute: MonCompteRoute,
  PipelineRoute: PipelineRoute,
  UtilisateursRoute: UtilisateursRoute,
  EntreprisesIdRoute: EntreprisesIdRoute,
  EntreprisesNouvelleRoute: EntreprisesNouvelleRoute,
  EntreprisesIdModifierRoute: EntreprisesIdModifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
